### ISSUE TITLE
개발, 프로덕션용 MongoDB 설정

### ISSUE THREAD

**Issue by seohyun0120** [mash-up-kr/TwoToo-Node#6]
- 개인 개발 환경에서는 알아서 mongodb를 띄워서 진행한다.
- 개발, 프로덕션 환경에서 사용할 MongoDB를 정하고, 설정해야한다.
(지원되는 NCP 환경도 검토)

**Comment by Hyun-git** [comment]
현재 DB를 어떻게 할지 고민 naver 클라우드 쓰면 달에 20만원 이상... 꽁짜로 받아서 쓴다고 해도 4개월 정도 쓸 수 있을 듯 아니면 그냥 구름 컨테이너 하나를 mongoDB용으로 쓰기 한 40기가 정도 되긴해서 쓸 수 는 있을듯

**Comment by Hyun-git** [comment]
로컬 DB연결 이후 env 설정 완료 -> s3연결만 하면 될듯
