### ISSUE TITLE
UTC 서버 시간 관련 이슈

### ISSUE THREAD

**Issue by seohyun0120** [mash-up-kr/TwoToo-Node#71]
DB에서는 전부 UTC 시간을 사용하고 있음
서버에서도 UTC시간을 사용하고 있다고 생각했으나 date-fns 패키지 확인이 필요
클라에서는 UTC+9 로 변환하여 사용하고 있음

"새벽 2시에 테스트했을때, 전날 커밋인증밖에 없는데도 이미 인증이 완료되었다는 에러 문구가 뜬다고 합니다."

**Comment by seohyun0120** [comment]
https://github.com/date-fns/date-fns/issues/3437

이 이슈 굉장히 의심스러움

**Comment by seohyun0120** [comment]
아이디어) process.env.TZ 설정하면 될 것 같기도 합니다.

**Comment by Hyun-git** [comment]
docker timezone으로 해결
