### ISSUE TITLE
[챌린지] 챌린지 API 명세에 맞춰 기본 틀을 구현한다.

### ISSUE THREAD

**Issue by seohyun0120** [mash-up-kr/TwoToo-Node#9]
API 명세는 노션에 있다.

- [x] - 챌린지 생성: `POST: /challenge`
- [x] - 챌린지 시작: `POST: /challenge/:challengeId/start`
- [x] - 챌린지 조회: `GET: /challenge/:challengeId`
- [x] - 챌린지 그만두기: `DELETE: /challenge:challengeId`
- [ ] - 정원 조회: `GET: /garden`

기본 틀을 작성한다. validation, error handling과 같이 추가적인 부분들은 다른 task로 분리하여 진행한다.

**Comment by LouiMinister** [comment]
정원 조회는 view 별 controller 만들 때 구현할게용
